name: Raspberry Pi 3 OpenWrt Firmware

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      release: 
        description: Upload compiled images to Release
        required: false
        default: 'true'
      upload-all:
        description: Upload all compiled images to Artifacts
        required: false
        default: 'false'

env:
  DOWNLOAD_BASE: https://downloads.openwrt.org
  VENDOR: openwrt
  VERSION: 23.05.4

jobs:
  Generate:
    runs-on: ubuntu-latest

    steps:
      - name: Initialization Environment
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip qemu-utils mkisofs

      - name: Setup Environment Variables
        run: |
          echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with: 
          path: origin

      - name: Download Image Builder
        run: |
          wget $DOWNLOAD_BASE/releases/$VERSION/targets/bcm27xx/bcm2710/$VENDOR-imagebuilder-$VERSION-bcm27xx-bcm2710.Linux-x86_64.tar.xz
          tar -xvf $VENDOR-imagebuilder-$VERSION-bcm27xx-bcm2710.Linux-x86_64.tar.xz
          rm -rf $VENDOR-imagebuilder-$VERSION-bcm27xx-bcm2710.Linux-x86_64.tar.xz
          cp -r $GITHUB_WORKSPACE/origin/* $GITHUB_WORKSPACE/$VENDOR-imagebuilder-$VERSION-bcm27xx-bcm2710.Linux-x86_64/
    
      - name: Run Patch and DIY Scripts
        working-directory: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-bcm27xx-bcm2710.Linux-x86_64
        run: |
          bash scripts/builder-patch-rpi3.sh

      - name: Generate Firmware
        working-directory: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-bcm27xx-bcm2710.Linux-x86_64
        run: |
          bbash package-openwrt/build-rpi3.sh

      - name: Upload VDI Image For Development Purpose
        if: github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.VENDOR }}-${{ env.VERSION }}-rpi3-vdi-image-${{ env.DATETIME }}
          path: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-bcm27xx-bcm2710.Linux-x86_64/bin/targets/bcm27xx/bcm2710/*.vdi

      - name: Upload All Firmware to Artifacts
        if: github.event.inputs.upload-all == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.VENDOR }}-${{ env.VERSION }}-rpi3-images-${{ env.DATETIME }}
          path: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-bcm27xx-bcm2710.Linux-x86_64/bin/targets/bcm27xx/bcm2710/*

      - name: Upload Firmware to Release
        if: github.event.inputs.release == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ env.VENDOR }}-imagebuilder-${{ env.VERSION }}-bcm27xx-bcm2710.Linux-x86_64/bin/targets/bcm27xx/bcm2710/*
          asset_name: ${{ github.event.repository.name }}-${{ github.sha }}
          tag: release-${{ env.DATE }}
          overwrite: true
